# Generated by Django 2.1.1 on 2018-09-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
