# Generated by Django 2.1.1 on 2018-10-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0002_remove_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
    ]
